[2022-11-06T03:33:35.938+0200] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_songs scheduled__2019-01-12T05:00:00+00:00 [queued]>
[2022-11-06T03:33:35.943+0200] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_songs scheduled__2019-01-12T05:00:00+00:00 [queued]>
[2022-11-06T03:33:35.944+0200] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T03:33:35.944+0200] {taskinstance.py:1363} INFO - Starting attempt 1 of 4
[2022-11-06T03:33:35.944+0200] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T03:33:35.953+0200] {taskinstance.py:1383} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-01-12 05:00:00+00:00
[2022-11-06T03:33:35.955+0200] {standard_task_runner.py:55} INFO - Started process 7745 to run task
[2022-11-06T03:33:35.961+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'udac_example_dag', 'Stage_songs', 'scheduled__2019-01-12T05:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/project/udac_example_dag.py', '--cfg-path', '/var/folders/sp/0_qfxj196m7gs6tyf69417g00000gn/T/tmp2p_0cst6']
[2022-11-06T03:33:35.962+0200] {standard_task_runner.py:83} INFO - Job 46: Subtask Stage_songs
[2022-11-06T03:33:36.002+0200] {task_command.py:376} INFO - Running <TaskInstance: udac_example_dag.Stage_songs scheduled__2019-01-12T05:00:00+00:00 [running]> on host mahmouds-macbook-pro.local
[2022-11-06T03:33:36.044+0200] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_example_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-01-12T05:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-12T05:00:00+00:00
[2022-11-06T03:33:36.049+0200] {base.py:71} INFO - Using connection ID 'aws_credentials' for task execution.
[2022-11-06T03:33:36.050+0200] {connection_wrapper.py:303} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2022-11-06T03:33:36.061+0200] {stage_redshift.py:78} INFO - Clearing data destination Redshift table
[2022-11-06T03:33:36.064+0200] {base.py:71} INFO - Using connection ID 'redshift' for task execution.
[2022-11-06T03:33:36.066+0200] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/mnagy99/airflow/plugins/operators/stage_redshift.py", line 79, in execute
    redshift_hook.run(f"TRUNCATE TABLE {self.table}") # Faster than DELETE FROM {self.table}
  File "/Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "redshift-cluster-1.cng0gslje4pq.us-west-2.redshift.amazonaws.com" to address: nodename nor servname provided, or not known

[2022-11-06T03:33:36.069+0200] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_songs, execution_date=20190112T050000, start_date=20221106T013335, end_date=20221106T013336
[2022-11-06T03:33:36.077+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 46 for task Stage_songs (could not translate host name "redshift-cluster-1.cng0gslje4pq.us-west-2.redshift.amazonaws.com" to address: nodename nor servname provided, or not known
; 7745)
[2022-11-06T03:33:36.109+0200] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-06T03:33:36.130+0200] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
